Documentation for Name Style in TimeZone
apple/swift-foundation pull request #176
Opened 2023-06-10 07:01 UTC by Roshankumar350

Added  documentation for Name Style in TimeZone.

2023-06-10 07:04 UTC, Roshankumar350 commented
Hello @iCharlesHu,
I have added one doc for `Name Style` in TimeZone. Please review and suggest :)

2023-07-28 18:10 UTC, Roshankumar350 commented
Hello @iCharlesHu, @parkera 
Waiting for review or suggestion :) Thanks

2023-07-31 21:18 UTC, iCharlesHu requested changes

2023-07-31 21:18 UTC, iCharlesHu commented on Sources/FoundationInternationalization/TimeZone/TimeZone.swift
> +///
We could omit this section as well since each case already has its own docs below already.

2023-08-01 22:30 UTC, iCharlesHu commented
@swift-ci please test

2023-08-01 22:30 UTC, itingliu commented on Sources/FoundationInternationalization/TimeZone/TimeZone.swift
> +/// Enum you use to specify different name style of a timezone.
Typo: "time zone" are two separate words

2023-08-03 18:45 UTC, Roshankumar350 commented
@swift-ci Please test

2023-08-20 18:32 UTC, Roshankumar350 commented
@iCharlesHu  @itingliu I have addressed you feedbacks. Please review

2023-09-19 21:39 UTC, Roshankumar350 commented
@iCharlesHu  Can you please have a look into this.

2023-11-07 23:04 UTC, iCharlesHu approved these changes

2023-11-07 23:04 UTC, merged