LockedState: Fix lock not being released when body throws
apple/swift-foundation pull request #97
Opened 2023-05-05 16:20 UTC by nonsensery

#### Summary

Currently, if the `body` closure passed to `withLockExtendingLifespanOfState(_:)` throws an error, the lock is not released. This PR fixes that.

#### Change

My fix was to switch the implementation of `withLockExtendingLifespanOfState(_:)` to delegate to `withLockUnchecked(_:)`, which does properly unlock if its body throws an error.

#### Verification

Added unit tests to verify this change, and backfilled tests that verify the lifespan-extending behavior of this method.

2023-05-05 20:25 UTC, glessard commented
Thanks Alex! Unfortunately we have two copies of this file (until we have the `package` access keyword!). Could you copy this fix to `FoundationInternationalization/LockedState.swift`?

2023-05-05 20:28 UTC, glessard requested changes
Thanks Alex! Unfortunately we have two copies of this file (until we have the package access keyword!). I applied the change to the other copy.

2023-05-05 20:52 UTC, iCharlesHu commented
@swift-ci please test

2023-05-08 04:45 UTC, glessard commented
@swift-ci please test

2023-05-08 18:54 UTC, parkera commented
We should get this fix in.

2023-05-08 20:14 UTC, glessard commented
@swift-ci please test

2023-05-08 20:17 UTC, glessard approved these changes
Thanks!

2023-05-08 20:40 UTC, merged

2023-05-08 20:49 UTC, glessard commented
Linked to rdar://109056170